### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources.py2_warn' 

### ISSUE THREAD

**Issue by longday24** [microsoft/vs-azure-iot-edge-docs#28]
Azure Iot Edge Tools : 1.7
Visual Studio Pro 2019 16.7.6

Received an update to Azure Iot Edge Tools Extension around 10/16/2020 : 10:30pm CST.

All calls to iotedgehubdev (c:\users\<redacted>\Documents\Visual Studio 2019\iotedgehubdev\v0.14.2\iotedgehubdev.exe)
now throw python package errors.

 `[11852] Failed to execute script pyi_rth_pkgres
Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
  File "d:\a\1\s\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[ERROR]: Failed to run 'iotedgehubdev setup -c HostName=brasherfarm.azure-devices.net;DeviceId=localdev;SharedAccessKey=xwmGIKdhB+/00lUjxZG+eNl8po/VCuntkoz2xwrR4oA=' with error: [11852] Failed to execute script pyi_rth_pkgres
Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
  File "d:\a\1\s\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn' `

I have verified the package py2_warn does exist in the same folder as __init__.py
Using pip install --upgrade iotedgehubdev (version: 0.11.1) works fine, but visual studio using the path to extension installed version(v0.14.2) fails.

**Comment by mrtncls** [comment]
I'm have the same issue.

Azure Iot Edge Tools: 1.7
Visual Studio Enterprise 2019 16.7.4

I tried reinstalling the extensions.
Also cleared folder c:\users\<user>\Documents\Visual Studio 2019\iotedgehubdev and ran 'Update Iot Edge simulator' but still have the same issue.

**Comment by mrtncls** [comment]
I found a workaround by installing https://pypi.org/project/iotedgehubdev/ into the default python env.

Steps I did:
 - pip install --upgrade iotedgehubdev (installs https://pypi.org/project/iotedgehubdev/ in the default python env)
 - notice the iotedgehubdev.exe in the install log
 - copy that exe into C:\Users\<user>\Documents\Visual Studio 2019\iotedgehubdev\default_python
 - set version to "default_python" in C:\Users\<version>\Documents\Visual Studio 2019\iotedgehubdev\simulator.config
 - vs will now use this install instead of C:\Users\<user>\Documents\Visual Studio 2019\iotedgehubdev\v0.14.2

**Comment by sdkryger** [comment]
I couldn't quite follow those directions... The following solution worked for me...

- pip install --upgrade iotedgehubdev (installs https://pypi.org/project/iotedgehubdev/ in the default python env) -  same first step

- Didn't know where iotedgehubdev.exe was installed. Didn't know how to find the install log. Found the file at the location C:\Users\<user>\AppData\Local\Programs\Python\Python39\Scripts

- Copy iotedgehubdev.exe from the above location and paste into location C:\Users\<user>\.vscode\extensions\vsciot-vscode.azure-iot-edge-1.23.0\iotedgehubdev\0.14.2 (Overwrite existing file in that location)

**Comment by asergaz** [comment]
The issue has been resolved in version 0.14.3 in the iotedgehub dev simulator and has been available to our customers since 10/22. VS and VS code extensions will automatically update to the newer version transparently, without the user intervention.

For more details on how the issue was fixed see: https://github.com/Azure/iotedgehubdev/issues/288

Please share here if there are any residual effects still blocking. After 10/22 everything is expected to just work without the user taking any additional action.

Thank you!

**Comment by asergaz** [comment]
#please-close

**Comment by konichi3** [comment]
Closing the issue
